name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    - name: build
      run: ./script/build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: xarcade-xinput
        path: XArcade XInput\bin\Release
